volumes:
  postgres_dir:

services:
  db:
    image: docker.io/postgres:18
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - postgres_dir:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
